
```{r}

dairy_df <- read_csv("data/dairy_dataset.csv", show_col_types = F) %>% clean_names()

dairy_df %>% distinct(customer_location) %>% pull(customer_location)
```
```{r}
dairy_df %>% 
  summarise(total_revenue = sum(approx_total_revenue_inr, na.rm = T), .by = c(product_name, farm_size)) %>% 
  arrange(desc(total_revenue))
```
```{r}
# Creating a dataframe with approximate latitude and longitude for the given locations
locations <- c("Madhya Pradesh", "Kerala", "Rajasthan", "Jharkhand", "Gujarat", "Karnataka",
               "Haryana", "Tamil Nadu", "West Bengal", "Telangana", "Chandigarh", "Maharashtra",
               "Delhi", "Bihar", "Uttar Pradesh")

# Approximate latitude and longitude coordinates for the locations (These are hypothetical values)
latitudes <- c(23.8141, 10.8505, 27.0238, 23.6102, 22.2587, 15.3173,
               29.0588, 11.1271, 22.9868, 17.1232, 30.7333, 19.7515,
               28.7041, 25.0961, 26.8467)

longitudes <- c(78.2691, 76.2711, 74.2179, 85.2799, 71.1924, 75.7139,
                76.0856, 78.6569, 87.8550, 79.2088, 76.7794, 75.7139,
                77.1025, 85.3131, 80.9462)

data <- data.frame(location = locations, latitude = latitudes, longitude = longitudes)

dairy_df <- dairy_df %>% inner_join(data, by = "location") 
  
revenue <- dairy_df %>% 
  summarise(total_revenue = sum(approx_total_revenue_inr, na.rm = T), .by = c(product_name, location)) %>% 
  arrange(desc(total_revenue)) %>% 
  inner_join(data, by = "location") 
  
leaflet(data = revenue) %>% 
  addTiles() %>%
  setView(lng = 78.9629, lat = 20.5937, zoom = 5) %>% 
  addCircleMarkers(
    lng = ~longitude,
    lat = ~latitude,
    radius = sqrt(revenue$total_revenue) / 50, # Adjust the radius size based on total revenue
    color = "red",
    fillOpacity = 0.7,
    popup = paste("Location: ", revenue$location, "<br>",
                  "Total Revenue: ", format(round(revenue$total_revenue, 0), big.mark = ", "))
  )
```
```{r}
library(maps)
mapStates = map("India", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
```





































